<a href="https://colab.research.google.com/github/Maxmuthee/Supervised-Machine-Learning/blob/main/Data_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
income=files.upload()

Saving DataTransformation.xlsx to DataTransformation.xlsx

In [ ]:
import pandas as pd
income = pd.read_excel("DataTransformation.xlsx")
display(income.head())

,age,workclass,education,education-num,occupation,sex,income
0,39,State-gov,Bachelors,13,Adm-clerical,Male,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Exec-managerial,Male,<=50K
2,38,Private,HS-grad,9,Handlers-cleaners,Male,<=50K
3,53,Private,11th,7,Handlers-cleaners,Male,<=50K
4,28,Private,Bachelors,13,Prof-specialty,Female,<=50K

In [ ]:
e_income = pd.get_dummies(income,dtype=int)
display(e_income.head())

,age,education-num,workclass_ ?,workclass_ Federal-gov,workclass_ Local-gov,workclass_ Never-worked,workclass_ Private,workclass_ Self-emp-inc,workclass_ Self-emp-not-inc,workclass_ State-gov,...,occupation_ Priv-house-serv,occupation_ Prof-specialty,occupation_ Protective-serv,occupation_ Sales,occupation_ Tech-support,occupation_ Transport-moving,sex_ Female,sex_ Male,income_ <=50K,income_ >50K
0,39,13,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,1,0
1,50,13,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,1,0
2,38,9,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,1,0
3,53,7,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,1,0
4,28,13,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,1,0,1,0

In [27]:
education_num = pd.get_dummies(income['education-num'], dtype=int)
display(education_num.head())

   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16
0   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0
1   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0
2   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0
3   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0
4   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0

In [28]:
#deserialization
import numpy as np
bins = np.linspace(max(e_income["age"]), min(e_income["age"]),5)#no of groupings
bins

array([90.  , 71.75, 53.5 , 35.25, 17.  ])

In [29]:
e_income["b_age"]=np.digitize(e_income["age"],bins=bins)
print(e_income)

       age  workclass_ ?  workclass_ Federal-gov  workclass_ Local-gov  \
0       39             0                       0                     0
1       50             0                       0                     0
2       38             0                       0                     0
3       53             0                       0                     0
4       28             0                       0                     0
...    ...           ...                     ...                   ...
32556   27             0                       0                     0
32557   40             0                       0                     0
32558   58             0                       0                     0
32559   22             0                       0                     0
32560   52             0                       0                     0

       workclass_ Never-worked  workclass_ Private  workclass_ Self-emp-inc  \
0                            0                   0                        0
1                            0                   0                        0
2                            0                   1                        0
3                            0                   1                        0
4                            0                   1                        0
...                        ...                 ...                      ...
32556                        0                   1                        0
32557                        0                   1                        0
32558                        0                   1                        0
32559                        0                   1                        0
32560                        0                   0                        1

       workclass_ Self-emp-not-inc  workclass_ State-gov  \
0                                0                     1
1                                1                     0
2                                0                     0
3                                0                     0
4                                0                     0
...                            ...                   ...
32556                            0                     0
32557                            0                     0
32558                            0                     0
32559                            0                     0
32560                            0                     0

       workclass_ Without-pay  ...  education-num_8  education-num_9  \
0                           0  ...                0                0
1                           0  ...                0                0
2                           0  ...                0                1
3                           0  ...                0                0
4                           0  ...                0                0
...                       ...  ...              ...              ...
32556                       0  ...                0                0
32557                       0  ...                0                1
32558                       0  ...                0                1
32559                       0  ...                0                1
32560                       0  ...                0                1

       education-num_10  education-num_11  education-num_12  education-num_13  \
0                     0                 0                 0                 1
1                     0                 0                 0                 1
2                     0                 0                 0                 0
3                     0                 0                 0                 0
4                     0                 0                 0                 1
...                 ...               ...               ...               ...
32556                 0                 0                 1                 0
32557                 0                 0                 0                 0
32558                 0                 0                 0                 0
32559                 0                 0                 0                 0
32560                 0                 0                 0                 0

       education-num_14  education-num_15  education-num_16  b_age
0                     0                 0                 0      3
1                     0                 0                 0      3
2                     0                 0                 0      3
3                     0                 0                 0      3
4                     0                 0                 0      4
...                 ...               ...               ...    ...
32556                 0                 0                 0      4
32557                 0                 0                 0      3
32558                 0                 0                 0      2
32559                 0                 0                 0      4
32560                 0                 0                 0      3

[32561 rows x 62 columns]

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
X=e_income.drop(columns=["income_ <=50K","income_ >50K"])
y=e_income["income_ <=50K"]
X_train, X_test, y_train, y_test= train_test_split(X, y, random_state = 0)# you can ignore the random state unless asked otherwise
LR = LogisticRegression(max_iter=1000).fit(X_train, y_train)#.fit() is for training
print("Training Accuracy: ", LR.score(X_train, y_train))
print("Testing Accuracy: ", LR.score(X_test, y_test))

Training Accuracy:  0.8088861588861589
Testing Accuracy:  0.8054293084387667